<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_pmra.docs.arlahc-sc.gc.ca</name>
   <tag></tag>
   <elementGuidId>c1352fcf-532b-4b39-ac14-37892fe8ee6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='section-2']/p/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3b586844-2498-4f60-9449-3765c0581caf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>mailto:pmra.docs.arla@hc-sc.gc.ca</value>
      <webElementGuid>bc6600fb-18ee-417e-bbcd-ee1e2917e54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>pmra.docs.arla@hc-sc.gc.ca</value>
      <webElementGuid>07c6edfa-ddd9-44b2-a7bd-78fa4b557c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-2&quot;)/p[1]/a[1]</value>
      <webElementGuid>521247db-270b-4acc-821b-3643f9704ee4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='section-2']/p/a</value>
      <webElementGuid>752b1aff-81e4-4209-ba19-43fed0dadb00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'pmra.docs.arla@hc-sc.gc.ca')]</value>
      <webElementGuid>c0e362e1-e767-4dc1-9c56-2c215d9fcc24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'mailto:pmra.docs.arla@hc-sc.gc.ca')]</value>
      <webElementGuid>dd37164a-486a-46ce-893c-90f74b87ebbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>53ec42d3-344d-4ef3-a1fa-692f24791416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'mailto:pmra.docs.arla@hc-sc.gc.ca' and (text() = 'pmra.docs.arla@hc-sc.gc.ca' or . = 'pmra.docs.arla@hc-sc.gc.ca')]</value>
      <webElementGuid>947b99bb-13c9-4b44-a9aa-039d554ce517</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
