<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>caption_Available forms</name>
   <tag></tag>
   <elementGuidId>059956e8-ed5a-4287-a567-0ce2aca6d9d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='indexTable']/caption</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>caption</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>caption</value>
      <webElementGuid>27576794-82e8-4c85-b7dd-a278ec9422df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Available forms</value>
      <webElementGuid>9c0af38a-6d6c-4436-80f6-d6e4e289a810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;indexTable&quot;)/caption[1]</value>
      <webElementGuid>6231fe8a-5934-4162-9af3-14bcf135f8f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='indexTable']/caption</value>
      <webElementGuid>e8289fdf-2a36-47aa-b69a-58f947a64f03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//caption</value>
      <webElementGuid>f5ce3bb3-9d7c-4916-b48e-19f528f720a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//caption[(text() = 'Available forms' or . = 'Available forms')]</value>
      <webElementGuid>b8393f38-4f68-466e-8577-49f1d4abd59a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
