<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Instructions for requesting PDF forms</name>
   <tag></tag>
   <elementGuidId>c07bfe26-b6b2-4cba-86b2-54abf7e68eaa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//details[@id='instructions']/summary/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h2.h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>ff075fc0-3d5a-4bae-ac44-5bbb6dc1c658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>729c7342-6652-4663-92b4-ce28759efa4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instructions for requesting PDF forms</value>
      <webElementGuid>b4d74bc9-6f09-42d8-a679-809c797fccae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;instructions&quot;)/summary[1]/h2[@class=&quot;h4&quot;]</value>
      <webElementGuid>0e90ce3c-babb-4682-a1c9-c0e252b558b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//details[@id='instructions']/summary/h2</value>
      <webElementGuid>d537a5b4-3359-4971-8aba-bfc7de5a59c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//summary/h2</value>
      <webElementGuid>0ba44f44-fcc0-4406-858b-8fd22946d28a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Instructions for requesting PDF forms' or . = 'Instructions for requesting PDF forms')]</value>
      <webElementGuid>563c25ab-8ced-47af-883a-e3c25e355512</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
