<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Support</name>
   <tag></tag>
   <elementGuidId>1edb0e7a-94c7-48a7-89fd-b85a7c5aa759</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//main/div/div/h2</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.px-2 > h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>c7216086-13cb-4662-a659-353c9e3839bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Support</value>
      <webElementGuid>e3a8d508-223b-4085-b5d0-b2695b314337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js backgroundsize borderimage csstransitions fontface svg details progressbar meter mathml cors js backgroundsize borderimage csstransitions fontface svg details progressbar meter no-mathml cors wb-enable xlargeview&quot;]/body[1]/main[@class=&quot;container&quot;]/div[@class=&quot;page&quot;]/div[@class=&quot;px-2&quot;]/h2[1]</value>
      <webElementGuid>4b17d70d-eb35-40b8-9ed8-5e307d0e7789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/h2</value>
      <webElementGuid>034b3f17-7b73-41f2-b441-3cfabcd330f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'Support' or . = 'Support')]</value>
      <webElementGuid>de94efae-2c7b-49c4-841c-e06e6e947015</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
