<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Forms in PDF format are available upon re_989b8d</name>
   <tag></tag>
   <elementGuidId>73f49adc-580b-4cdf-81fb-1101a0fa200c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//aside[@id='section-2']/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#section-2 > p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>bd19287e-2345-4801-9c92-168636c911b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Forms in PDF format are available upon request. Click on the form’s link from the table below to open an email addressed to pmra.docs.arla@hc-sc.gc.ca to submit your request. Ensure the text &quot;Request for form [your form number]&quot; is in the subject line of the email before sending.</value>
      <webElementGuid>59f4b88e-6035-4582-8def-82bc7e6eafd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;section-2&quot;)/p[1]</value>
      <webElementGuid>b6879746-3b43-4f1c-b19c-0b975b273efd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//aside[@id='section-2']/p</value>
      <webElementGuid>80727d3c-2e83-4865-9582-395b1462b015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//aside/p</value>
      <webElementGuid>02822915-97df-403d-aec1-d9cff05b8006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Forms in PDF format are available upon request. Click on the form’s link from the table below to open an email addressed to pmra.docs.arla@hc-sc.gc.ca to submit your request. Ensure the text &quot;Request for form [your form number]&quot; is in the subject line of the email before sending.' or . = 'Forms in PDF format are available upon request. Click on the form’s link from the table below to open an email addressed to pmra.docs.arla@hc-sc.gc.ca to submit your request. Ensure the text &quot;Request for form [your form number]&quot; is in the subject line of the email before sending.')]</value>
      <webElementGuid>3bd326e5-255a-4afa-a024-1e43987653e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
