<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>summary_Instructions for requesting PDF forms</name>
   <tag></tag>
   <elementGuidId>2b238fd6-34f5-40c8-a84f-5e87eeee1091</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//details[@id='instructions']/summary</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>summary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>64087ea0-000a-407c-b6ed-6c9922e5f7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Instructions for requesting PDF forms</value>
      <webElementGuid>83bece54-600e-4a01-b1ba-30b54913d80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;instructions&quot;)/summary[1]</value>
      <webElementGuid>b11d42fa-a2fb-454e-adca-ecfe83a42a2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//details[@id='instructions']/summary</value>
      <webElementGuid>9012cd36-6944-49a1-9095-fa465ea96621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//summary</value>
      <webElementGuid>c3614ac8-d58f-4c3a-b12d-6b2ad7bdbd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//summary[(text() = 'Instructions for requesting PDF forms' or . = 'Instructions for requesting PDF forms')]</value>
      <webElementGuid>59be26bc-e30d-4596-884e-2d4e5f9a7d51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
